### PR TITLE
Add bindings for PopLocalFrame and PushLocalFrame.

### PR DESCRIPTION
**Pull request by facundominguez**

### CODE REVIEW

**Comment by robinbb** [comment]
@alpmestan Is this the right place for this code?

@facundominguez Can we not catch the exception, and create a Haskell function that returns `Either () err` or itself throws a Haskell exception? We want to know if the JVM fails to execute either function; otherwise, the caller is not getting the functionality that they think they are.

**Comment by mboes** [comment]
@robinbb All `jni` functions can raise exceptions. That's already apparent in the type, because they all return `IO`. For better or for worse, `IO` includes the ability to both throw and catch exceptions from within it (https://www.schoolofhaskell.com/user/commercial/content/exceptions-best-practices includes a discussion about that point). Moreover, for most jni functions, if there's an exception, there isn't much else left to do but panic.

**Comment by robinbb** [comment]
@mboes You're saying that the exception should be caught within Haskell, as opposed to creating a JNI function which returns a success/fail value, I think?

**Comment by alpmestan** [comment]
@robinbb Yes, that's the idea.

**Pull request merged**
