### PR TITLE
leapyear-patchset reset

### PR DESCRIPTION
**Pull request by facundominguez**
@robinbb, please reset `leapyear-patchset` to this branch. Don't merge!

Make sure to tag the current leapyear-patchset so github preserves the commits for the history of the repos which point to inline-java.

Needed for https://github.com/LeapYear/leapyear-server/issues/949

### CODE REVIEW

**Comment by robinbb** [comment]
After fixing some errors with obvious solutions, I get the following when compiling sparkle with this inline-java branch:
```
   [1 of 1] Compiling Main             ( /Users/leapyear-robinbateboerop/repos/LeapYear/sparkle/Setup.hs, /Users/leapyear-robinbateboerop/repos/LeapYear/sparkle/.stack-work/dist/x86_64-osx-nix/Cabal-1.24.0.0/setup/Main.o )
    Linking /Users/leapyear-robinbateboerop/repos/LeapYear/sparkle/.stack-work/dist/x86_64-osx-nix/Cabal-1.24.0.0/setup/setup ...
    Configuring sparkle-0.4.0...
    Preprocessing library sparkle-0.4.0...
    [ 1 of 13] Compiling Control.Distributed.Spark.Iterator ( src/Control/Distributed/Spark/Iterator.hs, .stack-work/dist/x86_64-osx-nix/Cabal-1.24.0.0/build/Control/Distributed/Spark/Iterator.o )

    /Users/leapyear-robinbateboerop/repos/LeapYear/sparkle/src/Control/Distributed/Spark/Iterator.hs:44:1: error:
        • Unacceptable argument type in foreign declaration:
            ‘GHC.ForeignPtr.ForeignPtr
               (J ('Class
                     "java.lang.Object"))’ cannot be marshalled in a foreign call
        • When checking declaration:
            foreign export ccall "sparkle_iterator_next" sparkle_iterator_next
              :: Int64 -> JObject -> IO JObject

    /Users/leapyear-robinbateboerop/repos/LeapYear/sparkle/src/Control/Distributed/Spark/Iterator.hs:44:1: error:
        • Unacceptable result type in foreign declaration:
            ‘GHC.ForeignPtr.ForeignPtr
               (J ('Class
                     "java.lang.Object"))’ cannot be marshalled in a foreign call
        • When checking declaration:
            foreign export ccall "sparkle_iterator_next" sparkle_iterator_next
              :: Int64 -> JObject -> IO JObject
```

**Comment by facundominguez** [comment]
@robinbb, sparkle needs PR https://github.com/LeapYear/sparkle/issues/54

**Comment by robinbb** [comment]
Blocked on errors described in LeapYear/leapyear-server#949.

**Comment by robinbb** [comment]
Blocked on error described in LeapYear/leapyear-server#949.

**Comment by facundominguez** [comment]
Was a CI specific problem. Nothing related to the PR.

**Comment by facundominguez** [comment]
superseded by
https://github.com/LeapYear/leapyear-inline-java/pull/5

**Pull request closed without merging**
